[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run dev"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
autoDeploy = true

[env]
NODE_ENV = "production"
PORT = "5000"
APP_LANGUAGE = "en_EN"
TG_API_ID = "28403662"
TG_API_HASH = "079509d4ac7f209a1a58facd00d6ff5a"
TG_BOT_TOKEN = "8154976061:AAGryZFYIb5fu6OlCVFMAlWgiu6M8J9j_1o"
TG_AUTHORIZED_USER_ID = "6956029558"
TG_DOWNLOAD_PATH = "/app/data/downloads"
TG_SESSION = "/app/data/sessions/bottorrent"
PATH_CONFIG = "/app/data/tmp/config/config.ini"
PATH_PENDING_MESSAGES = "/app/data/tmp/config/pending_messages.json"
PATH_DOWNLOAD_FILES = "/app/data/tmp/config/download_files.json"
TG_MAX_PARALLEL = "4"
TG_DL_TIMEOUT = "3600"
YOUTUBE_AUDIO_FOLDER = "/app/data/downloads/youtube/audio"
YOUTUBE_VIDEO_FOLDER = "/app/data/downloads/youtube/videos"
ENABLED_UNZIP = "true"
ENABLED_UNRAR = "true"
ENABLED_7Z = "true"
TG_PROGRESS_DOWNLOAD = "true"