[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm run dev"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[service]
autoDeploy = true

[env]
NODE_ENV = "production"
# PORT will be set by Railway dynamically - don't override
FALLBACK_PORT = "5000"
APP_LANGUAGE = "en_EN"
# EXACT WORKSPACE SESSION STRING - Shakti_Kumar (@Ashaktihvc) for 100% replication
RAILWAY_SESSION_STRING = "1BVtsOMQBuyywtItcGyuFulZkrbUMRTcW4zveTMbISJ3pnzHZ1Y1e8zu5XU3tuKLNIo7k5AmtZ3TIqy5NSnypqibZoW1jfGYNzbQNyV-rx1sEqYS1x675ynrqX5yba5PwlphB4EMfIB3CmftFLdQ0YtfgeHVeFEvSNK1q37otbptsHhGLjzlP1HwrcrVksG7q3RqOzxmU1cE0YdC_JWQCWenx_-RLPJUpAObhy39oiYbvLAeNn09WdfsUdF5KWujyFYRRy9nwxbhh-TzenWzMQUOQN3vHfS9bvk21JfrxcHe_fUSKfqcINzo9ehGamN-PHY1y4BX4bfF51Yzhnv0m4Vrwm8j3yO8="
# Use same defaults as workspace (API_ID=21, API_HASH='default_hash')
# TG_API_ID = "28403662"  
# TG_API_HASH = "079509d4ac7f209a1a58facd00d6ff5a"
TG_BOT_TOKEN = "8154976061:AAGrNr6OcdMhFNhV5bCkpGfQAh0FYeJO1gE"
TG_AUTHORIZED_USER_ID = "6956029558"
# Use exact workspace folder structure - no volumes
TG_DOWNLOAD_PATH = "/app/downloads"
TG_SESSION = "/app/bottorrent.session"
PATH_CONFIG = "/app/config/config.ini"
PATH_PENDING_MESSAGES = "/app/config/pending_messages.json"
PATH_DOWNLOAD_FILES = "/app/config/download_files.json"
TG_MAX_PARALLEL = "4"
TG_DL_TIMEOUT = "3600"
# YouTube paths using exact workspace structure
YOUTUBE_AUDIO_FOLDER = "/app/downloads/youtube/audio"
YOUTUBE_VIDEO_FOLDER = "/app/downloads/youtube/videos"
# Enable all features exactly like workspace
ENABLED_UNZIP = "true"
ENABLED_UNRAR = "true"
ENABLED_7Z = "true"
ENABLED_YOUTUBE = "true"
TG_PROGRESS_DOWNLOAD = "true"
# Session paths for all components exactly like workspace
SESSION = "/app/bottorrent.session"
BOT_SESSION = "/app/bottorrent.session"
LIVE_CLONING_SESSION = "/app/bot_source/live-cloning/live_cloner"
COPIER_SESSION = "/app/tmp/config/copier"
# Use same defaults as workspace (empty env vars = fallback to API_ID=1, API_HASH='default_hash')
# API_ID = "28403662"
# API_HASH = "079509d4ac7f209a1a58facd00d6ff5a"
BOT_TOKEN = "8154976061:AAGrNr6OcdMhFNhV5bCkpGfQAh0FYeJO1gE"